---
- name: Combine data from multiple lists using map attribute
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Define lists of names and ages
      set_fact:
        names: ["Alice", "Bob", "Carol"]
        ages: [25, 30, 22]

    - name: Combine names and ages
      set_fact:
        people: "{{ people | default([]) + [{'name': item.0, 'age': item.1}] }}"
      loop: "{{ names | zip(ages) | list }}"

    - name: Display list of people
      debug:
        var: people

---
- name: Combine Data from Multiple Lists
  hosts: localhost
  vars:
    list1:
      - { "name": "Alice", "age": 30 }
      - { "name": "Bob", "age": 25 }
      - { "name": "Charlie", "age": 40 }
    
    list2:
      - { "name": "Alice", "city": "New York" }
      - { "name": "Bob", "city": "Los Angeles" }
      - { "name": "David", "city": "Chicago" }

  tasks:
    - name: Combine data based on 'name'
      debug:
        msg: "{{ list1 | product(list2) | map('combine') | selectattr('0.name', 'equalto', '1.name') | list }}"
