---
- name: Collecting the ansible_facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: collect facts
      setup:
    - name: Show details
      debug:
        msg: "{{ ansible_distribution }}"

    - name: Show details
      debug:
        msg: "{{ ansible_hostname }}"

    - name: Show details
      debug:
        msg: "{{ ansible_default_ipv4['address'] }}"
