---
- name: test playbook
  hosts: all
  gather_facts: true
  become: true

  tasks:
    # - name: installing the packages
    #   yum:
    #     - name: httpd
    #       state: latest
    #   when: ansible_distribution == 'Redhat'

    - name: installing the packages
      apt:
        name: nginx
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name:  debug the play
      debug:
        msg: "this playbook is ran successfully"


