---
- name: test playbook
  hosts: webserver
  gather_facts: true
  become: true
  vars:
    service_name: nginx
    yum_state: latest
    service_state: started
   
  tasks:
    - name: create the file using playbook
      yum:
        name: "{{ service_name }}"
        state: "{{ yum_state }}"

    - name: Start service httpd, if not started
      ansible.builtin.service:
         name: "{{ service_name }}"
         state: "{{  service_state }}"



  
