

---
- name: server test play
  hosts: webserver  # Use "hosts," not "host"
  gather_facts: true
  become: true
  vars:
    service_name: nginx
    yum_state: latest
    service_state: started
  tasks:
    - name: create file using playbook
      yum:
        name: "{{ service_name }}"
        state: "{{ yum_state }}"
    - name: Start the {{ service_name }} service
      service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"

