- hosts: localhost
  vars:
    listen_port: 80
    server_name: example.com
    document_root: /var/www/html

  tasks:
    - name: Generate nginx.conf
      template:
        src: ngnixconf.j2
        dest: /etc/nginx.conf
