---
- name: test playbook
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: create the file using playbook
      user:
        name: ec2-user
        shell: /bin/bash
        groups: ec2-user
        state: present
