---
- name: test playbook
  hosts: webserver
  gather_facts: true
  become: true
  tasks:
    - name: create the file using playbook
      file:
        path: /etc/arjun/test1
        state: touch
        owner: ec2-user
        group: "{{ group_name }}"
        mode: 600
