


---
- name: test playbook
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: create the user using playbook
      user:
        name: ec2-user
        shell: /bin/sh
        groups: root
        state: present


