---
- name: test playbook
  hosts: webserver
  gather_facts: true
  become: true
  vars:
    src_dir: /root/batch5/file2
    dest_dir: /etc/arjun/
  tasks:
    - name: create the file using playbook
      copy:
        src: "{{ src_dir }}"
        dest: "{{ dest_dir }}"
