---
- name: 'this playbook is to Create user'
  hosts: all
  become: true
  gather_facts: yes
  vars:
    pkg_names:
      - httpd
      - nginx
      - ansible-core
      

  tasks:
  - name: 'This task is refers to Create users'
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ pkg_names }}"
